version: '3'
services:  

  db:
    image: postgres:14.3
    volumes:
      - ./pg_updsrv_data:/var/lib/postgresql/data
      - ./migration/up:/docker-entrypoint-initdb.d
    environment:      
      POSTGRES_DB: updates
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1     
    command: >
      -c max_wal_size=2GB 
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - backend

  updsrv:
    build: 
      dockerfile: Dockerfile    
      context: .
    volumes:
      - .:/updsrv-config
    ports:
      - "8081:8081"
    restart: unless-stopped    
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:  
