version: '3'
services:  

  db:
    image: postgres:14.3
    volumes:
      - ./pg_log_data:/var/lib/postgresql/data
      - ./migration/up:/docker-entrypoint-initdb.d
    environment:      
      POSTGRES_DB: kp_logs
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1      
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - backend

  logsrv:
    build: 
      dockerfile: Dockerfile    
      context: .
    volumes:
      - .:/logsrv-config
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - logsrv.env
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:  
